system_packages:
  Debian:
    - { pkg: "htop", bin: "htop" }
    - { pkg: "sysstat", bin: "sar" }
    - { pkg: "traceroute", bin: "traceroute" }
    - { pkg: "iproute2", bin: "ip" }
    - { pkg: "curl", bin: "curl" }
    - { pkg: "wget", bin: "wget" }
    - { pkg: "zsh", bin: "zsh" }
  RedHat:
    - { pkg: "htop", bin: "htop" }
    - { pkg: "sysstat", bin: "sar" }
    - { pkg: "traceroute", bin: "traceroute" }
    - { pkg: "iproute", bin: "ip" }
    - { pkg: "curl", bin: "curl" }
    - { pkg: "wget", bin: "wget" }
    - { pkg: "zsh", bin: "zsh" }
