---
# Tasks for RedHat/CentOS systems

- name: Add Tailscale GPG key for RedHat-based systems
  rpm_key:
    state: present
    key: https://pkgs.tailscale.com/stable/rhel/{{ ansible_distribution_major_version }}/repo.gpg

- name: Add Tailscale repository for RedHat-based systems
  yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    baseurl: https://pkgs.tailscale.com/stable/rhel/$releasever
    gpgcheck: yes
    enabled: yes

- name: Update yum cache
  yum:
    update_cache: yes
