---
- name: SSH - Harden Configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: 'sshd -t -f %s'
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin', line: "PermitRootLogin {{ hardening_permit_root_login }}" }
    - { regexp: '^#?PasswordAuthentication', line: "PasswordAuthentication {{ hardening_password_auth }}" }
  notify: restart ssh
