---
- name: Update and upgrade all packages (Debian)
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    allow_downgrades: true
  when: ansible_facts['os_family'] == "Debian"

- name: Update all packages (RedHat/Fedora 43)
  ansible.builtin.package:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
