- name: Install base packages
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop: "{{ system_packages[ansible_facts['os_family']] | default(system_packages['Debian']) }}"
  loop_control:
    label: "{{ item.pkg }}"
