---

- hosts: all
  
  tasks:
    - name: Create ansible user
      user:
        name: ansible
        shell: /bin/bash
        create_home: true

    - name: Add ansible to admin group (distro-aware)
      user:
        name: ansible
        groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
        append: yes

    - name: Enable NOPASSWD sudo (distro-aware)
      copy:
        dest: "/etc/sudoers.d/ansible"
        content: "{{ '%wheel ALL=(ALL) NOPASSWD: ALL' if ansible_os_family == 'RedHat' else '%sudo ALL=(ALL) NOPASSWD: ALL' }}\n"
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
        
    - name: Ensure .ssh dir
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Adding public key (hardcoded)
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCR+YCc9AluIbnedoE0Ied8cG0CpnQBh2Mf4lYR71/x"

    - name: Ensure SSH listens on all interfaces
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ListenAddress'
        line: 'ListenAddress 0.0.0.0'
      notify: restart sshd
    
    - name: Firewall allow SSH from Tailscale
      firewalld:
        port: 22/tcp
        permanent: true
        state: enabled
      notify: reload firewalld

    - name: Create ansible-pull cron job
      cron:
        name: "Ansible-pull installing packages"
        minute: "*/1"
        job: "ansible-pull -U https://github.com/bhupinderhappy777/ansible -i inventory/hosts.ini playbooks/install-packages.yml >> /var/log/ansible-pull.log 2>&1"
        state: present
      notify: reload crond
    
  handlers:
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted
  
    - name: reload firewalld
      command: firewall-cmd --reload

    - name: reload crond 
      systemd:
        name: crond  
        state: reloaded

