---

- hosts: localhost
  connection: local
  
  tasks:
    - name: Create ansible user
      user:
        name: ansible
        shell: /bin/bash
        create_home: true

    - name: Add ansible to wheel group
      user:
        name: ansible
        groups: wheel
        append: yes

    - name: Enable NOPASSWD for wheel group
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel\s+ALL=\(ALL\)'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
        backup: yes  # Creates backup before change
