---

- hosts: localhost
  connection: local
  
  tasks:
    - name: Create ansible user
      user:
        name: ansible
        shell: /bin/bash
        create_home: true

    - name: Add ansible to wheel group
      user:
        name: ansible
        groups: wheel
        append: yes

    - name: Enable NOPASSWD for wheel group
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel\s+ALL=\(ALL\)'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
        backup: yes  # Creates backup before change

    - name: Ensure .ssh dir
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Adding public key (hardcoded)
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCR+YCc9AluIbnedoE0Ied8cG0CpnQBh2Mf4lYR71/x"

    - name: Ensure SSH listens on all interfaces
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ListenAddress'
        line: 'ListenAddress 0.0.0.0'
      notify: restart sshd
    
    - name: Firewall allow SSH from Tailscale
      firewalld:
        port: 22/tcp
        permanent: true
        state: enabled
      notify: reload firewalld
    
    handlers:
      - name: restart sshd
        systemd:
          name: sshd
          state: restarted
    
      - name: reload firewalld
        command: firewall-cmd --reload

